/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockDeliveryOracleInterface extends Interface {
  getFunction(
    nameOrSignature: "delivered" | "isDelivered" | "setDelivered"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "delivered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isDelivered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelivered",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "delivered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDelivered",
    data: BytesLike
  ): Result;
}

export interface MockDeliveryOracle extends BaseContract {
  connect(runner?: ContractRunner | null): MockDeliveryOracle;
  waitForDeployment(): Promise<this>;

  interface: MockDeliveryOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  delivered: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  isDelivered: TypedContractMethod<[id: BigNumberish], [boolean], "view">;

  setDelivered: TypedContractMethod<
    [id: BigNumberish, v: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "delivered"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDelivered"
  ): TypedContractMethod<[id: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "setDelivered"
  ): TypedContractMethod<[id: BigNumberish, v: boolean], [void], "nonpayable">;

  filters: {};
}
