/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  CreditScoreOracle,
  CreditScoreOracleInterface,
} from "../../credit/CreditScoreOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_u",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "score",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "at",
        type: "uint64",
      },
    ],
    name: "ScoreSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "u",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "scores",
    outputs: [
      {
        internalType: "uint16",
        name: "score",
        type: "uint16",
      },
      {
        internalType: "uint64",
        name: "updatedAt",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "u",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "s",
        type: "uint16",
      },
    ],
    name: "setScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "updater",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60803461007457601f6103ba38819003918201601f19168301916001600160401b038311848410176100795780849260209460405283398101031261007457516001600160a01b0381169081900361007457600080546001600160a01b03191691909117905560405161032a90816100908239f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe60806040818152600436101561001457600080fd5b600091823560e01c90816328dd9b391461014c5750806376dd110f146100ef578063d47875d0146100785763df034cd01461004e57600080fd5b34610074578160031936011261007457905490516001600160a01b039091168152602090f35b5080fd5b5034610074576020366003190112610074576020916100eb9082906001600160a01b036100a36102a3565b1681526001855220916100b46102be565b925461ffff811680855260109190911c67ffffffffffffffff16949093018490525191825260208201929092529081906040820190565b0390f35b5034610074576020366003190112610074576100eb9181906001600160a01b036101176102a3565b1681526001602090815291902054915161ffff8316815260109290921c67ffffffffffffffff16908201529081906040820190565b839150346100745782600319360112610074576101676102a3565b9060243561ffff928382169081830361029f5785546001600160a01b0394908516330361026f57506103e88211610240579561023a917fdc34a6bfebef956ac3ab1fca70a6583029a19e4e857a35ba563731cda862f50095969767ffffffffffffffff4216956101d56102be565b92835260208301918783521697888a526001602052838a2092511669ffffffffffffffff00008354925160101b169169ffffffffffffffffffff191617179055519283928390929167ffffffffffffffff60209161ffff604085019616845216910152565b0390a280f35b865162461bcd60e51b815260206004820152600860248201526706d617820313030360c41b6044820152606490fd5b62461bcd60e51b815260206004820152600b60248201526a3737ba103ab83230ba32b960a91b6044820152606490fd5b8580fd5b600435906001600160a01b03821682036102b957565b600080fd5b604051906040820182811067ffffffffffffffff8211176102de57604052565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220095bb9577600a7cf761d9574c4d97dacb1e47ec68d089ecdfb5650fc4b66317b64736f6c63430008180033";

type CreditScoreOracleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CreditScoreOracleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CreditScoreOracle__factory extends ContractFactory {
  constructor(...args: CreditScoreOracleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _u: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_u, overrides || {});
  }
  override deploy(
    _u: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_u, overrides || {}) as Promise<
      CreditScoreOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CreditScoreOracle__factory {
    return super.connect(runner) as CreditScoreOracle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CreditScoreOracleInterface {
    return new Interface(_abi) as CreditScoreOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CreditScoreOracle {
    return new Contract(address, _abi, runner) as unknown as CreditScoreOracle;
  }
}
