/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as harvestChainEscrowAiSol from "./HarvestChainEscrowAI.sol";
export type { harvestChainEscrowAiSol };
