/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICreditScoreOracle,
  ICreditScoreOracleInterface,
} from "../../../core/HarvestChainEscrowAI.sol/ICreditScoreOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        internalType: "uint16",
        name: "score",
        type: "uint16",
      },
      {
        internalType: "uint64",
        name: "updatedAt",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICreditScoreOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ICreditScoreOracleInterface {
    return new Interface(_abi) as ICreditScoreOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICreditScoreOracle {
    return new Contract(address, _abi, runner) as unknown as ICreditScoreOracle;
  }
}
