/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISSIRegistry,
  ISSIRegistryInterface,
} from "../../../core/HarvestChainEscrowAI.sol/ISSIRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "isAuthorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISSIRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ISSIRegistryInterface {
    return new Interface(_abi) as ISSIRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISSIRegistry {
    return new Contract(address, _abi, runner) as unknown as ISSIRegistry;
  }
}
