/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDeliveryOracle,
  IDeliveryOracleInterface,
} from "../../oracles/IDeliveryOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "isDelivered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDeliveryOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IDeliveryOracleInterface {
    return new Interface(_abi) as IDeliveryOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDeliveryOracle {
    return new Contract(address, _abi, runner) as unknown as IDeliveryOracle;
  }
}
